function ptriplews(varargin);
% ptriplews( [...] );
% Wind Speed
h = timeplot({'Wind_Speed','Wind_Speed'}, ...
      'Wind Speed', ...
      'Speed', ...
      {'Wind\_Speed','Wind\_Speed'}, ...
      varargin{:} );
