function ptriplehis(varargin);
% ptriplehis( [...] );
% Horiba Ion Source
h = timeplot({'IonSource_SP','IonSource'}, ...
      'Horiba Ion Source', ...
      'Ion Source', ...
      {'IonSource\_SP','IonSource'}, ...
      varargin{:} );
