function ptriplehr(varargin);
% ptriplehr( [...] );
% Horiba Reagent
h = timeplot({'Reagent_SP','Reagent'}, ...
      'Horiba Reagent', ...
      'Reagent', ...
      {'Reagent\_SP','Reagent'}, ...
      varargin{:} );
