function ptriplewd(varargin);
% ptriplewd( [...] );
% Wind Dir
h = timeplot({'Wind_Dir','Wind_Dir'}, ...
      'Wind Dir', ...
      'Dir', ...
      {'Wind\_Dir','Wind\_Dir'}, ...
      varargin{:} );
