function ptriplexdsf(varargin);
% ptriplexdsf( [...] );
% nXDS Freq
h = timeplot({'nX0MtrF','nX1MtrF'}, ...
      'nXDS Freq', ...
      'Freq', ...
      {'nX0MtrF','nX1MtrF'}, ...
      varargin{:} );
