function ptriplefsp(varargin);
% ptriplefsp( [...] );
% Flows Set Pts
h = timeplot({'ScrubMFCset','DiluteMFCset','IonSourceMFCset','ReagentMFCset'}, ...
      'Flows Set Pts', ...
      'Set Pts', ...
      {'ScrubMFCset','DiluteMFCset','IonSourceMFCset','ReagentMFCset'}, ...
      varargin{:} );
