function ptriplehd(varargin);
% ptriplehd( [...] );
% Horiba Dilution
h = timeplot({'Dilution_SP','Dilution'}, ...
      'Horiba Dilution', ...
      'Dilution', ...
      {'Dilution\_SP','Dilution'}, ...
      varargin{:} );
