function ptripleupsstatw(varargin);
% ptripleupsstatw( [...] );
% UP Sstat Warn
h = timeplot({'UPS_Warn'}, ...
      'UP Sstat Warn', ...
      'Warn', ...
      {'UPS\_Warn'}, ...
      varargin{:} );
