function ptripleiwg1_stattd(varargin);
% ptripleiwg1_stattd( [...] );
% IWG1 Stat T Drift
h = timeplot({'TDDrift','TDrift','TDDrift','TDrift'}, ...
      'IWG1 Stat T Drift', ...
      'T Drift', ...
      {'TDDrift','TDrift','TDDrift','TDrift'}, ...
      varargin{:} );
