function ptriplehstale(varargin);
% ptriplehstale( [...] );
% Horiba Stale
h = timeplot({'Horiba_Stale'}, ...
      'Horiba Stale', ...
      'Stale', ...
      {'Horiba\_Stale'}, ...
      varargin{:} );
