function ptripleass(varargin);
% ptripleass( [...] );
% Attitude Side Slip
h = timeplot({'Side_slip','Side_slip'}, ...
      'Attitude Side Slip', ...
      'Side Slip', ...
      {'Side\_slip','Side\_slip'}, ...
      varargin{:} );
