function ptriplead(varargin);
% ptriplead( [...] );
% Attitude Drift
h = timeplot({'Drift','Drift'}, ...
      'Attitude Drift', ...
      'Drift', ...
      {'Drift','Drift'}, ...
      varargin{:} );
