function ptripleiwgs(varargin);
% ptripleiwgs( [...] );
% IWG1 Speed
h = timeplot({'Grnd_Spd','Indicated_Airspeed','True_Airspeed','Grnd_Spd','Indicated_Airspeed','True_Airspeed'}, ...
      'IWG1 Speed', ...
      'Speed', ...
      {'Grnd\_Spd','Indicated\_Airspeed','True\_Airspeed','Grnd\_Spd','Indicated\_Airspeed','True\_Airspeed'}, ...
      varargin{:} );
