function ptripleaaz(varargin);
% ptripleaaz( [...] );
% Attitude AZ
h = timeplot({'Sun_Az_AC','Sun_Az_AC'}, ...
      'Attitude AZ', ...
      'AZ', ...
      {'Sun\_Az\_AC','Sun\_Az\_AC'}, ...
      varargin{:} );
