function ptripleiwg1_statcp(varargin);
% ptripleiwg1_statcp( [...] );
% IWG1 Stat Cabin Press
h = timeplot({'Cabin_Press','Cabin_Press'}, ...
      'IWG1 Stat Cabin Press', ...
      'Cabin Press', ...
      {'Cabin\_Press','Cabin\_Press'}, ...
      varargin{:} );
