function ptripleupsstatg(varargin);
% ptripleupsstatg( [...] );
% UP Sstat Grp
h = timeplot({'UPS_Group'}, ...
      'UP Sstat Grp', ...
      'Grp', ...
      {'UPS\_Group'}, ...
      varargin{:} );
