function ptripleupsv(varargin);
% ptripleupsv( [...] );
% UPS V
h = timeplot({'UPS_V_in','UPS_V_out','UPS_VBusP','UPS_VBusN','UPS_VBatP','UPS_VBatN'}, ...
      'UPS V', ...
      'V', ...
      {'UPS\_V\_in','UPS\_V\_out','UPS\_VBusP','UPS\_VBusN','UPS\_VBatP','UPS\_VBatN'}, ...
      varargin{:} );
