function ptriplecs(varargin);
% ptriplecs( [...] );
% Commands Status
h = ne_dstat({
  'E1200A', 'H_DIO_A', 7; ...
	'E1200B', 'H_DIO_B', 7; ...
	'D1200A', 'H_DIO_D', 0; ...
	'D1200B', 'H_DIO_D', 1; ...
	'LensHV', 'H_DIO_C', 7; ...
	'fan1', 'H_DIO_D', 4; ...
	'fan2', 'H_DIO_D', 5; ...
	'fan3', 'H_DIO_D', 6; ...
	'DigIn7', 'H_DIO_D', 7; ...
	'Flowtube_pumping', 'H_DIO_D', 2; ...
	'turbo_pumping', 'H_DIO_D', 3 }, 'Status', varargin{:} );
