function ptriplenxds1s(varargin);
% ptriplenxds1s( [...] );
% nXDS1 Stat
h = ne_dstat({
  'nX1_Power', 'nX1Power', 0; ...
	'nX1_V802', 'nX0Power', 1; ...
	'nX1_Resp', 'nX1Stat', 0; ...
	'nX1_Dec', 'nX1Stat', 1; ...
	'nX1_Acc', 'nX1Stat', 2; ...
	'nX1_Stdby', 'nX1Stat', 3; ...
	'nX1_Full', 'nX1Stat', 4; ...
	'nX1_AbvRamp', 'nX1Stat', 5; ...
	'nX1_AbvOvLd', 'nX1Stat', 6; ...
	'nX1_Warn', 'nX1Stat', 7; ...
	'nX1_Fault', 'nX1Stat', 8; ...
	'nX1_OV', 'nX1Stat', 9; ...
	'nX1_OI', 'nX1Stat', 10; ...
	'nX1_OT', 'nX1Stat', 11; ...
	'nX1_UT', 'nX1Stat', 12; ...
	'nX1_PwrStgFlt', 'nX1Stat', 13; ...
	'nX1_OLTO', 'nX1Stat', 14; ...
	'nX1_AccTO', 'nX1Stat', 15 }, 'Stat', varargin{:} );
