function ptriplemfcs(varargin);
% ptriplemfcs( [...] );
% MFC Status
h = ne_dstat({
  'ScrubMFC_Open', 'H_DIO_E', 0; ...
	'ScrubMFC_Close', 'H_DIO_E', 1; ...
	'DiluteMFC_Open', 'H_DIO_E', 2; ...
	'DiluteMFC_Close', 'H_DIO_E', 3; ...
	'IonSourceMFC_Open', 'H_DIO_E', 4; ...
	'IonSourceMFC_Close', 'H_DIO_E', 5; ...
	'ReagentMFC_Open', 'H_DIO_E', 6; ...
	'ReagentMFC_Close', 'H_DIO_E', 7 }, 'Status', varargin{:} );
