function ptripleap(varargin);
% ptripleap( [...] );
% Attitude Pitch
h = timeplot({'Pitch','Pitch'}, ...
      'Attitude Pitch', ...
      'Pitch', ...
      {'Pitch','Pitch'}, ...
      varargin{:} );
