function ptripleiwg1_stats(varargin);
% ptripleiwg1_stats( [...] );
% IWG1 Stat Stale
h = timeplot({'IWG1_Stale','IWG1_Stale'}, ...
      'IWG1 Stat Stale', ...
      'Stale', ...
      {'IWG1\_Stale','IWG1\_Stale'}, ...
      varargin{:} );
