function ptripleat(varargin);
% ptripleat( [...] );
% Attitude Track
h = timeplot({'Track','True_Hdg','Track','True_Hdg'}, ...
      'Attitude Track', ...
      'Track', ...
      {'Track','True\_Hdg','Track','True\_Hdg'}, ...
      varargin{:} );
