function ptriplewvs(varargin);
% ptriplewvs( [...] );
% Wind Vert Speed
h = timeplot({'Vert_Wind_Spd','Vert_Wind_Spd'}, ...
      'Wind Vert Speed', ...
      'Vert Speed', ...
      {'Vert\_Wind\_Spd','Vert\_Wind\_Spd'}, ...
      varargin{:} );
