function ptripleupsstatr(varargin);
% ptripleupsstatr( [...] );
% UP Sstat Response
h = timeplot({'UPS_Response'}, ...
      'UP Sstat Response', ...
      'Response', ...
      {'UPS\_Response'}, ...
      varargin{:} );
