function ptriplesparet(varargin);
% ptriplesparet( [...] );
% Spare T
h = timeplot({'TSpare1','TSpare2'}, ...
      'Spare T', ...
      'T', ...
      {'TSpare1','TSpare2'}, ...
      varargin{:} );
