function ptripleff(varargin);
% ptripleff( [...] );
% Flows Flows
h = timeplot({'ScrubMFC','DiluteMFC','IonSourceMFC','ReagentMFC','cidMFC','MainFlowMeter'}, ...
      'Flows Flows', ...
      'Flows', ...
      {'ScrubMFC','DiluteMFC','IonSourceMFC','ReagentMFC','cidMFC','MainFlowMeter'}, ...
      varargin{:} );
