function ptripleiwgm(varargin);
% ptripleiwgm( [...] );
% IWG1 Mach
h = timeplot({'Mach_Number','Mach_Number'}, ...
      'IWG1 Mach', ...
      'Mach', ...
      {'Mach\_Number','Mach\_Number'}, ...
      varargin{:} );
