function ptripleptt(varargin);
% ptripleptt( [...] );
% PT Temps
h = timeplot({'MainFlowTherm','ChemIonTherm','TurboPumpT','TempIC'}, ...
      'PT Temps', ...
      'Temps', ...
      {'MainFlowTherm','ChemIonTherm','TurboPumpT','TempIC'}, ...
      varargin{:} );
