function ptriplegs(varargin);
% ptriplegs( [...] );
% Greek Status
h = ne_dstat({
  'VBeta1', 'H_DIO_B', 1; ...
	'VBeta6', 'H_DIO_B', 6; ...
	'VGamma5', 'H_DIO_C', 5; ...
	'VGamma6', 'H_DIO_C', 6 }, 'Status', varargin{:} );
