function ptriplea_az(varargin);
% ptriplea_az( [...] );
% Attitude Az
h = timeplot({'Sun_Az_Grd','Sun_Az_Grd'}, ...
      'Attitude Az', ...
      'Az', ...
      {'Sun\_Az\_Grd','Sun\_Az\_Grd'}, ...
      varargin{:} );
