function ptripleaa(varargin);
% ptripleaa( [...] );
% Attitude Attack
h = timeplot({'Angle_of_Attack','Angle_of_Attack'}, ...
      'Attitude Attack', ...
      'Attack', ...
      {'Angle\_of\_Attack','Angle\_of\_Attack'}, ...
      varargin{:} );
