function ptriplewvv(varargin);
% ptriplewvv( [...] );
% Wind Vert Vel
h = timeplot({'Vert_Velocity','Vert_Velocity'}, ...
      'Wind Vert Vel', ...
      'Vert Vel', ...
      {'Vert\_Velocity','Vert\_Velocity'}, ...
      varargin{:} );
