#ifndef SWSTAT_H_INCLUDED
#define SWSTAT_H_INCLUDED
#define SWS_INLET_IDLE 5
#define SWS_INLET_PRESSURE 6
#define SWS_DITHER_ONE 7
#define SWS_DITHER_END 8
#define SWS_SCRUB_READY 9
#define SWS_DITHER_DATA 10
#define SWS_DITHER_DRYCAL 11
#define SWS_DITHER_AMBCAL 12
#define SWS_DITHER_ZERO 13
#define SWS_DITHER_SITZERO 14
#define SWS_DITHER_SITAMBCAL 15
#define SWS_DITHER_SIT_POSDATA 16
#define SWS_DITHER_TWO 17
#define SWS_DITHER_THREE 18
#define SWS_DITHER_WATER 19
#define SWS_DITHER_WATER2 20
#define SWS_SITON_DATA 21
#define SWS_SITON_NEG_DATAwMHP 22
#define SWS_SITON_NEG_DRYZERO 23
#define SWS_SITON_NEG_DRYCAL 24
#define SWS_SITON_NEG_AMBZERO 25
#define SWS_SITON_POS_AMBCAL 26
#define SWS_INIT_CONTINUE 27
#define SWS_AUTOCALTRIPLE_START 28
#define SWS_AUTOCALTRIPLE_STOP 29
#define SWS_TRIP_SUS 253
#define SWS_LAB_READ 254
#define SWS_SHUTDOWN 255

#endif
