function pToFtwistorrb(varargin);
% pToFtwistorrb( [...] );
% Twis Torr Bflags
h = ne_dstat({
  'TTB_Start', 'TTB_flags', 0; ...
	'TTB_Speed', 'TTB_flags', 1; ...
	'TTB_WtrCl', 'TTB_flags', 2; ...
	'TTB_ActStp', 'TTB_flags', 3; ...
	'TTB_VentVlv', 'TTB_flags', 4; ...
	'TTB_VentOp', 'TTB_flags', 5; ...
	'TTB_Resp', 'TTB_flags', 7 }, 'Bflags', varargin{:} );
