function pToFsats(varargin);
% pToFsats( [...] );
% gpsd sats
h = timeplot({'satellites_visible','satellites_used'}, ...
      'gpsd sats', ...
      'sats', ...
      {'satellites\_visible','satellites\_used'}, ...
      varargin{:} );
