function pToFttettb(varargin);
% pToFttettb( [...] );
% TT Errors TTB
h = ne_dstat({
  'TTB_NoConn', 'TTB_ErrStat', 0; ...
	'TTB_PumpOT', 'TTB_ErrStat', 1; ...
	'TTB_CtrlOT', 'TTB_ErrStat', 2; ...
	'TTB_PwrFail', 'TTB_ErrStat', 3; ...
	'TTB_AuxFail', 'TTB_ErrStat', 4; ...
	'TTB_OverV', 'TTB_ErrStat', 5; ...
	'TTB_Short', 'TTB_ErrStat', 6; ...
	'TTB_OverLoad', 'TTB_ErrStat', 7; ...
	'TTB_LowBatt', 'TTB_ErrStat', 9; ...
	'TTB_BadTime', 'TTB_ErrStat', 10 }, 'TTB', varargin{:} );
