function pToFtwistorrs(varargin);
% pToFtwistorrs( [...] );
% Twis Torr Speed
h = timeplot({'TTA_drvf','TTA_spd','TTB_drvf','TTB_spd'}, ...
      'Twis Torr Speed', ...
      'Speed', ...
      {'TTA\_drvf','TTA\_spd','TTB\_drvf','TTB\_spd'}, ...
      varargin{:} );
