function pToFhis(varargin);
% pToFhis( [...] );
% Horiba Ion Src
h = timeplot({'IonSrcFlow','IonSrcFlowSP'}, ...
      'Horiba Ion Src', ...
      'Ion Src', ...
      {'IonSrcFlow','IonSrcFlowSP'}, ...
      varargin{:} );
