function pToFtwistorrstale(varargin);
% pToFtwistorrstale( [...] );
% Twis Torr Stale
h = timeplot({'TT_stale'}, ...
      'Twis Torr Stale', ...
      'Stale', ...
      {'TT\_stale'}, ...
      varargin{:} );
