function pToFttetta(varargin);
% pToFttetta( [...] );
% TT Errors TTA
h = ne_dstat({
  'TTA_NoConn', 'TTA_ErrStat', 0; ...
	'TTA_PumpOT', 'TTA_ErrStat', 1; ...
	'TTA_CtrlOT', 'TTA_ErrStat', 2; ...
	'TTA_PwrFail', 'TTA_ErrStat', 3; ...
	'TTA_AuxFail', 'TTA_ErrStat', 4; ...
	'TTA_OverV', 'TTA_ErrStat', 5; ...
	'TTA_Short', 'TTA_ErrStat', 6; ...
	'TTA_OverLoad', 'TTA_ErrStat', 7; ...
	'TTA_LowBatt', 'TTA_ErrStat', 9; ...
	'TTA_BadTime', 'TTA_ErrStat', 10 }, 'TTA', varargin{:} );
