function pToFhzf(varargin);
% pToFhzf( [...] );
% Horiba Zero Flow
h = timeplot({'ZeroFlow_SP','ZeroFlow'}, ...
      'Horiba Zero Flow', ...
      'Zero Flow', ...
      {'ZeroFlow\_SP','ZeroFlow'}, ...
      varargin{:} );
