function pToFhd(varargin);
% pToFhd( [...] );
% Horiba Dilution
h = timeplot({'DilFlow','DilFlowSP'}, ...
      'Horiba Dilution', ...
      'Dilution', ...
      {'DilFlow','DilFlowSP'}, ...
      varargin{:} );
