function pToFirisstale(varargin);
% pToFirisstale( [...] );
% Iris Stale
h = timeplot({'Z1stale','Zstale'}, ...
      'Iris Stale', ...
      'Stale', ...
      {'Drive','Driver'}, ...
      varargin{:} );
