function pToFtwistorrv(varargin);
% pToFtwistorrv( [...] );
% Twis Torr V
h = timeplot({'TTA_V','TTB_V'}, ...
      'Twis Torr V', ...
      'V', ...
      {'TTA\_V','TTB\_V'}, ...
      varargin{:} );
