function pToFhhp(varargin);
% pToFhhp( [...] );
% Horiba Horiba P
h = timeplot({'HoribaP_SP','HoribaP'}, ...
      'Horiba Horiba P', ...
      'Horiba P', ...
      {'HoribaP\_SP','HoribaP'}, ...
      varargin{:} );
