function pToFtc(varargin);
% pToFtc( [...] );
% Turbos Current
h = timeplot({'TPA_Cmon','TPB_Cmon'}, ...
      'Turbos Current', ...
      'Current', ...
      {'TPA\_Cmon','TPB\_Cmon'}, ...
      varargin{:} );
