function pToFupsstatstale(varargin);
% pToFupsstatstale( [...] );
% UP Sstat Stale
h = timeplot({'UPS_Stale'}, ...
      'UP Sstat Stale', ...
      'Stale', ...
      {'UPS\_Stale'}, ...
      varargin{:} );
