function pToFgdt(varargin);
% pToFgdt( [...] );
% Gas Deck Temp
h = timeplot({'T1','T3','T4','CalT'}, ...
      'Gas Deck Temp', ...
      'Temp', ...
      {'T1','T3','T4','CalT'}, ...
      varargin{:} );
