function pToFhs(varargin);
% pToFhs( [...] );
% Horiba Status
h = ne_dstat({
  'DilFlowSP_S', 'HoribaS', 0; ...
	'IonSrcFlowSP_S', 'HoribaS', 2; ...
	'FFlowSP_S', 'HoribaS', 4; ...
	'HoribaPSP_S', 'HoribaS', 6; ...
	'DilFlow_S', 'HoribaS', 1; ...
	'IonSrcFlow_S', 'HoribaS', 3; ...
	'FFlow_S', 'HoribaS', 5; ...
	'HoribaP_S', 'HoribaS', 7; ...
	'DilCmd_S', 'HoribaS', 8; ...
	'IonCmd_S', 'HoribaS', 9; ...
	'FlCmd_S', 'HoribaS', 10 }, 'Status', varargin{:} );
