function pToFhff(varargin);
% pToFhff( [...] );
% Horiba F Flow
h = timeplot({'FFlow_SP','FFlow'}, ...
      'Horiba F Flow', ...
      'F Flow', ...
      {'FFlow\_SP','FFlow'}, ...
      varargin{:} );
