function pToFiwg1_stats(varargin);
% pToFiwg1_stats( [...] );
% IWG1 Stat Stale
h = timeplot({'IWG1_Stale'}, ...
      'IWG1 Stat Stale', ...
      'Stale', ...
      {'IWG1\_Stale'}, ...
      varargin{:} );
