function pToFhisf(varargin);
% pToFhisf( [...] );
% Horiba Ion Src Flow
h = timeplot({'IonSrcFlow_SP','IonSrcFlow'}, ...
      'Horiba Ion Src Flow', ...
      'Ion Src Flow', ...
      {'IonSrcFlow\_SP','IonSrcFlow'}, ...
      varargin{:} );
