function pToFgpsd_errclimb(varargin);
% pToFgpsd_errclimb( [...] );
% gpsd err climb
h = timeplot({'gpsd_epc'}, ...
      'gpsd err climb', ...
      'climb', ...
      {'gpsd\_epc'}, ...
      varargin{:} );
