function pToFgcs(varargin);
% pToFgcs( [...] );
% Gas Cmds Status
h = ne_dstat({
  'AmbZeroS', 'AII_DS0', 0; ...
	'Bypass_cal', 'Herc_DS_A', 0; ...
	'Scrub_cal', 'Herc_DS_A', 1; ...
	'H2O2_cal', 'Herc_DS_A', 2; ...
	'Oacid_cal', 'Herc_DS_A', 3; ...
	'MHP_cal', 'Herc_DS_A', 4; ...
	'Spare1_cal', 'Herc_DS_A', 5; ...
	'Spare2_cal', 'Herc_DS_A', 6; ...
	'Amb_zero', 'Herc_DS_A', 7 }, 'Status', varargin{:} );
