function pToFiwgs(varargin);
% pToFiwgs( [...] );
% IWG1 Speed
h = timeplot({'Grnd_Spd','Indicated_Airspeed','True_Airspeed'}, ...
      'IWG1 Speed', ...
      'Speed', ...
      {'Grnd\_Spd','Indicated\_Airspeed','True\_Airspeed'}, ...
      varargin{:} );
