function pToFtstatus(varargin);
% pToFtstatus( [...] );
% Turbos Status
h = ne_dstat({
  'TPB_Enb', 'Herc_DS_C', 4; ...
	'TPA_Enb', 'Herc_DS_C', 5; ...
	'TPA_Start', 'Herc_DS_C', 6; ...
	'TPB_Start', 'Herc_DS_D', 0; ...
	'TPA_Low', 'Herc_DS_C', 7; ...
	'TPB_Low', 'Herc_DS_D', 1 }, 'Status', varargin{:} );
