function pToFtwistorra(varargin);
% pToFtwistorra( [...] );
% Twis Torr Aflags
h = ne_dstat({
  'TTA_Start', 'TTA_flags', 0; ...
	'TTA_Speed', 'TTA_flags', 1; ...
	'TTA_WtrCl', 'TTA_flags', 2; ...
	'TTA_ActStp', 'TTA_flags', 3; ...
	'TTA_VentVlv', 'TTA_flags', 4; ...
	'TTA_VentOp', 'TTA_flags', 5; ...
	'TTA_Resp', 'TTA_flags', 7 }, 'Aflags', varargin{:} );
