function pToFoa(varargin);
% pToFoa( [...] );
% Octopole Amp
h = timeplot({'Oct_Amp_RB','Oct_Amp_sp'}, ...
      'Octopole Amp', ...
      'Amp', ...
      {'Oct\_Amp\_RB','Oct\_Amp\_sp'}, ...
      varargin{:} );
