function pToFgdmbar(varargin);
% pToFgdmbar( [...] );
% Gas Deck mbar
h = timeplot({'INTP','CALP','InH_P','InL_P','PT_P'}, ...
      'Gas Deck mbar', ...
      'mbar', ...
      {'INTP','CALP','InH\_P','InL\_P','PT\_P'}, ...
      varargin{:} );
