function pToFhcf(varargin);
% pToFhcf( [...] );
% Horiba Cal Flow
h = timeplot({'CalFlow_SP','CalFlow'}, ...
      'Horiba Cal Flow', ...
      'Cal Flow', ...
      {'CalFlow\_SP','CalFlow'}, ...
      varargin{:} );
