function pToFob(varargin);
% pToFob( [...] );
% Octopole Bias
h = timeplot({'Oct_Bias_RB','Oct_Bias_sp'}, ...
      'Octopole Bias', ...
      'Bias', ...
      {'Oct\_Bias\_RB','Oct\_Bias\_sp'}, ...
      varargin{:} );
