function pToFgdt(varargin);
% pToFgdt( [...] );
% Gas Deck Temp
h = timeplot({'T1','T3','T3_1Hz','T4','T4_1Hz','CalT'}, ...
      'Gas Deck Temp', ...
      'Temp', ...
      {'T1','T3','T3\_1Hz','T4','T4\_1Hz','CalT'}, ...
      varargin{:} );
