function pToFtwistorrt(varargin);
% pToFtwistorrt( [...] );
% Twis Torr T
h = timeplot({'TTA_T','TTB_T'}, ...
      'Twis Torr T', ...
      'T', ...
      {'TTA\_T','TTB\_T'}, ...
      varargin{:} );
