function pToFtwistorrw(varargin);
% pToFtwistorrw( [...] );
% Twis Torr W
h = timeplot({'TTA_W','TTB_W'}, ...
      'Twis Torr W', ...
      'W', ...
      {'TTA\_W','TTB\_W'}, ...
      varargin{:} );
