function pToFhcal2flow(varargin);
% pToFhcal2flow( [...] );
% Horiba Cal 2 Flow
h = timeplot({'Cal2Flow_SP','Cal2Flow'}, ...
      'Horiba Cal 2 Flow', ...
      'Cal 2 Flow', ...
      {'Cal2Flow\_SP','Cal2Flow'}, ...
      varargin{:} );
