function pToFhdf(varargin);
% pToFhdf( [...] );
% Horiba Dil Flow
h = timeplot({'DilFlow_SP','DilFlow'}, ...
      'Horiba Dil Flow', ...
      'Dil Flow', ...
      {'DilFlow\_SP','DilFlow'}, ...
      varargin{:} );
