function pToFupsstats(varargin);
% pToFupsstats( [...] );
% UP Sstat Status
h = timeplot({'UPS_Status'}, ...
      'UP Sstat Status', ...
      'Status', ...
      {'UPS\_Status'}, ...
      varargin{:} );
