function pToFaa(varargin);
% pToFaa( [...] );
% Attitude Attack
h = timeplot({'Angle_of_Attack'}, ...
      'Attitude Attack', ...
      'Attack', ...
      {'Angle\_of\_Attack'}, ...
      varargin{:} );
