function pToFtwistorri(varargin);
% pToFtwistorri( [...] );
% Twis Torr I
h = timeplot({'TTA_I','TTB_I'}, ...
      'Twis Torr I', ...
      'I', ...
      {'TTA\_I','TTB\_I'}, ...
      varargin{:} );
