function pGPStestgpsd_toffsec(varargin);
% pGPStestgpsd_toffsec( [...] );
% gpsd toff sec
h = timeplot({'gpsd_real_sec','gpsd_clock_sec'}, ...
      'gpsd toff sec', ...
      'sec', ...
      {'gpsd\_real\_sec','gpsd\_clock\_sec'}, ...
      varargin{:} );
