function pGPStestgpsd_errtime(varargin);
% pGPStestgpsd_errtime( [...] );
% gpsd err time
h = timeplot({'gpsd_ept'}, ...
      'gpsd err time', ...
      'time', ...
      {'gpsd\_ept'}, ...
      varargin{:} );
