function pGPStestgpsd_statuserror(varargin);
% pGPStestgpsd_statuserror( [...] );
% gpsd status error
h = ne_dstat({
  'gpsd_time_err_set', 'gpsd_err_status', 0; ...
	'gpsd_h_err_set', 'gpsd_err_status', 1; ...
	'gpsd_v_err_set', 'gpsd_err_status', 2; ...
	'gpsd_speed_err_set', 'gpsd_err_status', 3; ...
	'gpsd_track_err_set', 'gpsd_err_status', 4; ...
	'gpsd_climb_err_set', 'gpsd_err_status', 5; ...
	'gpsd_error_set', 'gpsd_err_status', 6 }, 'error', varargin{:} );
